#!/usr/bin/env zsh

PURPLE="#5F00AF"
DARK_ORANGE="#613620"
ZERODARK_BLUEDARK="#1f5582"
GREEN="#427b58"
SECONDARY="#d3869b"
ACCENT="#923D3D"

# daemon config
# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 8 9 0

bspc config window_gap            20
bspc config border_width          2
bspc config split_ratio           0.52

# bspc config focused_border_color $ZERODARK_BLUEDARK
bspc config focused_border_color $ACCENT
bspc config normal_border_color  $DARK_ORANGE

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer false
bspc config click_to_focus        true

bspc config pointer_modifier mod4 # mod4 = super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Gimp state=floating follow=on
bspc rule -a Pqiv state=tiled
bspc rule -a Tilda state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Libreoffice state=tiled
bspc rule -a libreoffice-calc state=tiled

# xinitrc migration
# arch specific stuff
# see: https://www.reddit.com/r/archlinux/comments/6o2il3/script_in_xinitrcd_not_running_automatically/
if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [[ -x "$f" ]] && source "$f"
  done
  unset f
fi

# heavy daemons
# command -v udiskie > /dev/null 2>&1 && udiskie &
command -v dropbox-cli > /dev/null 2>&1 && dropbox-cli start &

# Xorg configurations
XREC=~/.Xresources; [[ -f $XREC ]] && xrdb -merge $XREC
MODMAP=~/.Xmodmap;  [[ -f $MODMAP ]] && xmodmap $MODMAP

# daemons
sxhkd &
# xchainkeys &
# mpd &

# tip from: https://darryldias.me/06/bspwm-on-debian/
xsetroot -cursor_name left_ptr &

# visual effects

# ------------------------------------
# daemon spawn section
kill_proc() {
  pgrep -f $1 >/dev/null && pkill -9 -f $1
}

# launch polybar
kill_proc polybar
~/.config/polybar/launch.sh &

# start emacs daemon
kill_proc emacs
~/.dotfiles/scripts/emacs/up-emacs-daemon.sh &

# start redshift
kill_proc redshift
redshift -c ~/.options/arch/redshift/redshift.conf &

# greenclip: clear history and spawn
greenclip clear
kill_proc greenclip
greenclip daemon &

# wallpaper
# feh --bg-fill ~/Dropbox/pics/wall/chromecast/horizonte.jpg
# feh --bg-fill ~/Dropbox/pics/wall/autism-leaves.png
feh --bg-fill ~/Dropbox/pics/juli/DSCF0207.jpg

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg.pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT SSH_AUTH_SOCK

# network manager
nm-applet &

# java WM/bspwm specific nuisance
wmname LG3D

# compton
# compton --config ~/.options/arch/compton/compton.conf -b
