#!/usr/bin/env zsh

# daemon config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap            20
bspc config border_width          1
bspc config split_ratio           0.52

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true
bspc config click_to_focus        true

bspc config pointer_modifier mod4 # mod4 = super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Gimp state=floating follow=on
bspc rule -a Pqiv state=tiled
bspc rule -a Tilda state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Libreoffice state=tiled
bspc rule -a libreoffice-calc state=tiled

# visual effects
setroot --center --zoom ~/Dropbox/pics/wall/red.jpg
compton &
~/.config/polybar/launch.sh &

# heavy apps
GTK_IM_MODULE=xim google-chrome-stable --force-device-scale-factor=1.3 &
~/.dotfiles/scripts/emacs/up-emacs-daemon.sh &
