#!/usr/bin/env zsh

PURPLE="#5F00AF"
DARK_ORANGE="#613620"
ZERODARK_BLUEDARK="#1f5582"

# daemon config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap            20
bspc config border_width          4
bspc config split_ratio           0.52

bspc config focused_border_color $ZERODARK_BLUEDARK
bspc config normal_border_color  $DARK_ORANGE

bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer false
bspc config click_to_focus        true

bspc config pointer_modifier mod4 # mod4 = super
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# rules
bspc rule -a Emacs state=tiled
bspc rule -a Gimp state=floating follow=on
bspc rule -a Pqiv state=tiled
bspc rule -a Tilda state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Libreoffice state=tiled
bspc rule -a libreoffice-calc state=tiled

# visual effects
feh --bg-fill ~/Dropbox/pics/wall/dark-arch.png

~/.config/polybar/launch.sh &

# start emacs daemon
~/.dotfiles/scripts/emacs/up-emacs-daemon.sh &
