# This tmux statusbar config was created by tmuxline.vim
# on Wed, 06 Jul 2016

set -g status-bg "colour237"
set -g message-command-fg "colour235"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g pane-active-border-fg "colour208"
set -g message-bg "colour243"
set -g status-right-length "100"
set -g status-right-attr "none"
set -g message-fg "colour235"
set -g message-command-bg "colour243"
set -g status-attr "none"
set -g pane-border-fg "colour243"
set -g status-left-attr "none"
setw -g window-status-fg "colour246"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour237"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour208"
setw -g window-status-separator ""
setw -g window-status-bg "colour237"
set -g status-left "#[fg=colour235,bg=colour208] #S #[fg=colour208,bg=colour237,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour243,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour243] %Y-%m-%d | %H:%M #[fg=colour208,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour208] #h "
setw -g window-status-format "#[fg=colour246,bg=colour237] #I |#[fg=colour246,bg=colour237] #W "
setw -g window-status-current-format "#[fg=colour237,bg=colour243,nobold,nounderscore,noitalics]#[fg=colour235,bg=colour243] #I |#[fg=colour235,bg=colour243] #W #[fg=colour243,bg=colour237,nobold,nounderscore,noitalics]"
