#+STARTUP: indent
#+STARTUP: overview

* Emacs

#+BEGIN_QUOTE
"Emacs outshines all other editing software in approximately
the same way that the noonday sun does the stars. It is not
just bigger and brighter; it simply makes everything else
vanish."
(Neal Stephenson, "In the Beginning was the Command Line")
#+END_QUOTE

#+BEGIN_QUOTE
"Show me your ~/.emacs and I will tell you who you are."
(Bogdan Maryniuk)
#+END_QUOTE

#+BEGIN_QUOTE
"Emacs is like a laser guided missile. It only has to be
slightly mis-configured to ruin your whole day."
(Sean McGrathi)
#+END_QUOTE

#+BEGIN_QUOTE
"Lisp isn't a language, it's a building material."
(Alan Kay)
#+END_QUOTE

#+BEGIN_QUOTE
"Compared to Emacs Wizards, graphical-IDE users are the
equivalent of amateur musicians, pawing at their instrument
with a sort of desperation. An IDE has blinking lights and
pretty dialogs that you can't interact with properly, and
gives newbies a nice comfortable sense of control. But that
control is extremely crude, and all serious programmers
prefer something that gives them more power."
(Steve Yegge)
#+END_QUOTE

#+BEGIN_QUOTE
Saying that Emacs is just a text editor is like calling iPhone just a
phone.
([[http://www.terminally-incoherent.com/blog/2007/12/13/emacs-with-auctex-as-a-latex-ide/][Luke - Terminally Incoherent]])
#+END_QUOTE

#+BEGIN_QUOTE
While any text editor can save your files, only Emacs can save your
soul.
(Per Abrahamsen)
#+END_QUOTE

#+BEGIN_QUOTE
The reasonable man adapts himself to Emacs; the unreasonable one
persists in trying to adapt Emacs to himself. Therefore all progress
depends on the unreasonable man.
(G.B. Shaw)
#+END_QUOTE

* Ninrod's Emacs configuration
- use-package for managing dependencies
- org-babel to keep the init.el organized as an org-mode file.
- ivy instead of helm

* List of emacs paint points comming from vim
** basic editing operations
- [[https://bitbucket.org/lyro/evil/issues/726/vt-vf-vt-vf-vt-vf-vt-vf-do-not-work][`vt'` and `vt"` do not work with us-internationl keyboard deadkeys]]
- `diw` in a sequence of spaces eats `\n` if applied in a line break.
- `yiw` does not move cursor to beggining of text object.
- does emacs have virtual columns?
- the star operator is broken when subword-mode is active.
** Completions
- tab completion with dabbrev-expand ignores case.
** Missing plugins
- wellle/targets.vim (evil-targets)
- terryma/multiple cursors (evil-multiple-cursors)
- junegunn/easyalign (evil-align)
** Terminal issues
- clipboard integration
- truecolor support
- dinamycally alter cursor shape based on state
