* layers configuration notice

Configuration Layers declaration. 
You should not put any user code in this function besides modifying the variable values.
* base distribution

Base distribution to use. This is a layer contained in the directory `+distribution'. 
For now available distributions are `spacemacs-base' or `spacemacs'. 
(default 'spacemacs)

#+BEGIN_SRC emacs-lisp
  (setq-default dotspacemacs-distribution 'spacemacs)
#+END_SRC

* layer lazy installation
** doc
Lazy installation of layers. layers are installed only when a file with a supported type is opened. 
*** Possible values are: `all', `unused' and `nil': 
**** 'unused (default)
will lazy install only unused layers layers not listed in variable `dotspacemacs-configuration-layers')
**** 'all 
will lazy install any layer that support lazy installation even the layers
listed in `dotspacemacs-configuration-layers'. 
**** nil 
disable the lazy installation feature and you have to explicitly list a layer in the
variable `dotspacemacs-configuration-layers' to install it.
** code
#+BEGIN_SRC emacs-lisp
   dotspacemacs-enable-lazy-installation 'unused
#+END_SRC
* [cleanup]: layers variables
#+BEGIN_SRC emacs-lisp
  (setq-default
   ;; If non-nil then Spacemacs will ask for confirmation before installing
   ;; a layer lazily. (default t)
   dotspacemacs-ask-for-lazy-installation t
   ;; If non-nil layers with lazy install support are lazy installed.
   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()
   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------

     org
     emacs-lisp
     version-control
     git
     shell
     helm
     ivy

     vim-empty-lines
     evil-commentary

     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     )
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   dotspacemacs-additional-packages '()
   ;; A list of packages that cannot be updated.
   dotspacemacs-frozen-packages '()
   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages '()
   ;; Defines the behaviour of Spacemacs when downloading packages.
   ;; Possible values are `used', `used-but-keep-unused' and `all'. `used' will
   ;; download only explicitly used packages and remove any unused packages as
   ;; well as their dependencies. `used-but-keep-unused' will download only the
   ;; used packages but won't delete them if they become unused. `all' will
   ;; download all the packages regardless if they are used or not and packages
   ;; won't be deleted by Spacemacs. (default is `used')
   dotspacemacs-download-packages 'used)
#+END_SRC
* local org options
#+STARTUP: indent
#+STARTUP: overview
